In [1]:
print("all ok")

all ok


### One Hot Encoder

In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [2]:
documents = ["people watch movie", 
             "people watch cricket", 
             "people like movie", 
             "people like cricket"]

In [3]:
token = [sentence.lower().split() for sentence in documents]

In [5]:
token

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

In [4]:
all_words = [[word] for sentence in token for word in sentence]

In [5]:
print(all_words)

[['people'], ['watch'], ['movie'], ['people'], ['watch'], ['cricket'], ['people'], ['like'], ['movie'], ['people'], ['like'], ['cricket']]


In [7]:
Encoder = OneHotEncoder(sparse_output = False)

In [8]:
Encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

In [9]:
print("Vocabulary:", Encoder.categories_[0])

Vocabulary: ['cricket' 'like' 'movie' 'people' 'watch']


In [11]:
for sentence in token:
    print(sentence)

['people', 'watch', 'movie']
['people', 'watch', 'cricket']
['people', 'like', 'movie']
['people', 'like', 'cricket']


In [12]:
for sentence in token:
    encoded_sentence = Encoder.transform([[word]for word in sentence])

In [14]:
print("\n Sentence:" ,sentence)
print(encoded_sentence)


 Sentence: ['people', 'like', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


### BOW - BAG OF WORDS

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:

documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]

In [17]:
bow = CountVectorizer()

In [18]:
bow.fit_transform(documents)

<4x8 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [19]:
bow_matrix = bow.fit_transform(documents)

In [21]:
print("Bow matrix:\n" ,bow_matrix.toarray())

Bow matrix:
 [[1 1 0 0 0 2 1 2]
 [0 1 2 0 0 0 1 2]
 [0 1 0 2 1 2 1 0]
 [0 0 1 1 0 0 1 0]]


In [22]:
print("BOW Matrix:\n", bow_matrix.toarray())

BOW Matrix:
 [[1 1 0 0 0 2 1 2]
 [0 1 2 0 0 0 1 2]
 [0 1 0 2 1 2 1 0]
 [0 0 1 1 0 0 1 0]]


In [23]:
bow.get_feature_names_out()

array(['again', 'and', 'cricket', 'like', 'lot', 'movie', 'people',
       'watch'], dtype=object)

In [24]:
print(" Vocabulary:" ,bow.get_feature_names_out())

 Vocabulary: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']


### TF - IDF

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
tf_idf = TfidfVectorizer()

In [28]:

documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]

In [29]:
tf_id_vector = tf_idf.fit_transform(documents)

In [30]:
tf_id_vector

<4x8 sparse matrix of type '<class 'numpy.float64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [31]:
tf_id_vector.toarray()

array([[0.38771136, 0.24747114, 0.        , 0.        , 0.        ,
        0.61135218, 0.20232387, 0.61135218],
       [0.        , 0.2684707 , 0.66322944, 0.        , 0.        ,
        0.        , 0.21949239, 0.66322944],
       [0.        , 0.24747114, 0.        , 0.61135218, 0.38771136,
        0.61135218, 0.20232387, 0.        ],
       [0.        , 0.        , 0.64043405, 0.64043405, 0.        ,
        0.        , 0.42389674, 0.        ]])

In [32]:
for vector in tf_id_vector.toarray():
    print(vector)

[0.38771136 0.24747114 0.         0.         0.         0.61135218
 0.20232387 0.61135218]
[0.         0.2684707  0.66322944 0.         0.         0.
 0.21949239 0.66322944]
[0.         0.24747114 0.         0.61135218 0.38771136 0.61135218
 0.20232387 0.        ]
[0.         0.         0.64043405 0.64043405 0.         0.
 0.42389674 0.        ]


In [33]:
tf_idf.get_feature_names_out()

array(['again', 'and', 'cricket', 'like', 'lot', 'movie', 'people',
       'watch'], dtype=object)

In [34]:
print("Vocabulary:" , tf_idf.get_feature_names_out())

Vocabulary: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']


In [35]:
print("Vocabulary:" , tf_idf.get_feature_names_out())

Vocabulary: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']
